services:
  web:
    build: .
    image: fapitemplate:dev
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env.development
    volumes:
      - .:/app